str_1 = "Hello"
str_2 = "World"
concatenating_both_string = str_1 + str_2
print(concatenating_both_string)

Greetings = " Hello \t World"
print(Greetings)

my_str = "Hello world" * 2
print(my_str)

uu = "HELLO WORLD,HI," * 2
number_of_charather = uu.count("HELLO WORLD")
print(number_of_charather)


formullaitu = "greeting"
student_in_uppercase = str.upper(formullaitu)
print(student_in_uppercase)

formula = "GREETING"
lower = str.lower(formula)
print(lower)


manner = "greeting"
x = "greeting01".swap(manner)
print(x)
