username_set={"ram123","sita45","hari88"}
print(type(username_set))

username_set={"ram123","sita45","hari88","ram123"}
print(username_set)
# because set store only unique items only so in the above code the name ram123 is repeated twice a row so it does'nt mean unique.
mixed_set=2,'hello',(1,2)
print(mixed_set)

print('ram123'in username_set)

mixed_set_2=2,'hello',[1,2]
print(type(mixed_set_2))



